# Generated by Django 4.2.2 on 2023-07-14 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=999)),
                ('release_date', models.CharField(max_length=100)),
                ('poster_url', models.CharField(max_length=255)),
                ('age_rating', models.IntegerField()),
                ('ticket_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_id', models.IntegerField()),
                ('purchase_date', models.DateField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.moviedata')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.userdata')),
            ],
        ),
    ]
